package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/Sahil2k07/graphql/internal/graphql/generated"
	"github.com/Sahil2k07/graphql/internal/utils"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input generated.CreateTodoInput) (*generated.Todo, error) {
	res, err := r.TodoService.CreateTodo(ctx, input)
	if err != nil {
		return nil, utils.HandleGraphQLError(ctx, err)
	}

	return res, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input generated.UpdateTodoInput) (*generated.Todo, error) {
	res, err := r.TodoService.UpdateTodo(ctx, input)
	if err != nil {
		return nil, utils.HandleGraphQLError(ctx, err)
	}

	return res, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (string, error) {
	res, err := r.TodoService.DeleteTodo(ctx, id)
	if err != nil {
		return "", utils.HandleGraphQLError(ctx, err)
	}

	return res, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, page *int, limit *int) (*generated.TodoPage, error) {
	res, err := r.TodoService.GetTodos(ctx, page, limit)
	if err != nil {
		return nil, utils.HandleGraphQLError(ctx, err)
	}

	return res, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*generated.Todo, error) {
	res, err := r.TodoService.GetTodoByID(ctx, id)
	if err != nil {
		return nil, utils.HandleGraphQLError(ctx, err)
	}

	return res, nil
}
