FROM golang:1.25.3-alpine3.22 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod tidy

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=mod -o main ./cmd/server

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=builder /app/main .

CMD [ "./main" ]